### ISSUE TITLE
Prediction fails on Red Hat OpenShift

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Audio-Classifier#38]
The following error is raised, when a prediction is performed:
```

[2019-08-05 21:56:03,078] ERROR in app: Exception on /model/predict [POST]
--
  | Traceback (most recent call last):
  | File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/conda/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
  | resp = resource(*args, **kwargs)
  | File "/opt/conda/lib/python3.6/site-packages/flask/views.py", line 88, in view
  | return self.dispatch_request(*args, **kwargs)
  | File "/opt/conda/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
  | resp = meth(*args, **kwargs)
  | File "/opt/conda/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
  | resp = f(*args, **kwargs)
  | File "/workspace/api/predict.py", line 63, in post
  | file = open("audio.wav", "wb")
  | PermissionError: [Errno 13] Permission denied: 'audio.wav'

```

The issue is that the code assumes that it has write access in the current working directory https://github.com/IBM/MAX-Audio-Classifier/blob/master/api/predict.py#L59-L89. The temporary audio file should be created in a temporary location that any user should have write access to.

**Comment by kmh4321** [comment]
Should there be a `os.chmod('audio.wav', 777)` command below this block?
https://github.com/IBM/MAX-Audio-Classifier/blob/master/api/predict.py#L62

**Comment by bdwyer2** [comment]
I have opened #39 to fix this. Once it is merged in I will open the same PR on the audio embedding generator model

**Comment by ptitzler** [comment]
Confirmed that predictions work using the latest image on RH OS.
