### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by JackieWouuu** [IBM/MAX-Audio-Classifier#80]
Hello, I'm having problems when lauching the program. 
This is the errors i'm getting : 

2023-10-04 16:51:06 Traceback (most recent call last):
2023-10-04 16:51:06   File "app.py", line 17, in <module>
2023-10-04 16:51:06     from api import ModelMetadataAPI, ModelPredictAPI
2023-10-04 16:51:06   File "/home/max/api/__init__.py", line 16, in <module>
2023-10-04 16:51:06     from .metadata import ModelMetadataAPI  # noqa
2023-10-04 16:51:06   File "/home/max/api/metadata.py", line 16, in <module>
2023-10-04 16:51:06     from core.model import ModelWrapper
2023-10-04 16:51:06   File "/home/max/core/model.py", line 19, in <module>
2023-10-04 16:51:06     import tensorflow as tf
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow/__init__.py", line 102, in <module>
2023-10-04 16:51:06     from tensorflow_core import *
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 28, in <module>
2023-10-04 16:51:06     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
2023-10-04 16:51:06   File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
2023-10-04 16:51:06     module = self._load()
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
2023-10-04 16:51:06     module = _importlib.import_module(self.__name__)
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
2023-10-04 16:51:06     return _bootstrap._gcd_import(name[level:], package, level)
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
2023-10-04 16:51:06     from tensorflow.core.framework.graph_pb2 import *
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 16, in <module>
2023-10-04 16:51:06     from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/core/framework/node_def_pb2.py", line 16, in <module>
2023-10-04 16:51:06     from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/core/framework/attr_value_pb2.py", line 16, in <module>
2023-10-04 16:51:06     from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_pb2.py", line 16, in <module>
2023-10-04 16:51:06     from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/core/framework/resource_handle_pb2.py", line 16, in <module>
2023-10-04 16:51:06     from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/core/framework/tensor_shape_pb2.py", line 42, in <module>
2023-10-04 16:51:06     serialized_options=None, file=DESCRIPTOR),
2023-10-04 16:51:06   File "/opt/conda/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 561, in __new__
2023-10-04 16:51:06     _message.Message._CheckCalledFromGeneratedFile()
2023-10-04 16:51:06 TypeError: Descriptors cannot not be created directly.
2023-10-04 16:51:06 If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
2023-10-04 16:51:06 If you cannot immediately regenerate your protos, some other possible workarounds are:
2023-10-04 16:51:06  1. Downgrade the protobuf package to 3.20.x or lower.
2023-10-04 16:51:06  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
2023-10-04 16:51:06 
2023-10-04 16:51:06 More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

I tried installing an older version of protobuf (3.20) and forcing it in the requirements.txt, i put the lastest version of tensorflow
Any idea what i'm doing wrong ? 
Thanks

**Comment by JackieWouuu** [comment]
I added streamlit==1.9.0 in requirements.txt and it fixed it ...
